[package]
edition = "2021"
name = "njupt_wifi_login"
version = "0.1.3"

[dependencies]
hyper = {version = "0.14.18", default-features = false}
log = "0.4"
log4rs = "1.2"
once_cell = "1.15.0"
regex = "1"
reqwest = {version = "0.11.14", default-features = false}
serde = {version = "1", features = ["derive"]}
serde_yaml = "0.9.14"
serde_json = "1"
thiserror = "1"
tokio = {version = "1", features = ["full"]}
trust-dns-resolver = "0.22.0"
const_format = "0.2.30"
lazy_static = "1"
anyhow = "1"

[dependencies.windows]
features = [
  "Win32_Foundation",
  "Win32_Networking_WinSock",
  "Win32_NetworkManagement_IpHelper",
]
version = "0.46"
