[package]
edition = "2021"
name = "njupt_wifi_login"
version = "0.1.0"

[dependencies]
config = "0.13"
log = "0.4"
log4rs = "1.2"
regex = "1"
reqwest = {version = "0.11"}
serde = {version = "1", features = ["derive"]}
thiserror = "1"
tokio = {version = "1", features = ["full"]}

[dependencies.windows]
features = [
  "Win32_Foundation",
  "Win32_Networking_WinSock",
  "Win32_NetworkManagement_IpHelper",
]
version = "0.42"
