[package]
edition = "2021"
name = "njupt_wifi_login"
version = "0.1.3"

[dependencies]
hyper = {version = "0.14.18", default-features = false}
once_cell = "1.15.0"
regex = "1"
reqwest = {version = "0.11.14", default-features = false}
serde = {version = "1", features = ["derive"]}
serde_yaml = "0.9.14"
serde_json = "1"
thiserror = "1"
tokio = {version = "1", features = ["full"]}
const_format = "0.2"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-appender = "0.2"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.44", features = [
  "Win32_Foundation",
  "Win32_Networking_WinSock",
  "Win32_NetworkManagement_IpHelper",
]}

[target.'cfg(target_os = "linux")'.dependencies]
futures = "0.3"
netlink-sys = "0.8"
netlink-packet-core = "0.5"
netlink-packet-route = "0.15"
rtnetlink = "0.12"
libc = "0.2"
