[package]
edition = "2021"
name = "njupt_wifi_login"
version = "0.1.1"

[dependencies]
log = "0.4"
log4rs = "1.2"
once_cell = "1.15.0"
regex = "1"
reqwest = {version = "0.11"}
serde = {version = "1", features = ["derive"]}
serde_yaml = "0.9.14"
thiserror = "1"
tokio = {version = "1", features = ["full"]}

[dependencies.windows]
features = [
  "Win32_Foundation",
  "Win32_Networking_WinSock",
  "Win32_NetworkManagement_IpHelper",
]
version = "0.42"
