[package]
edition = "2021"
name = "njupt_wifi_login_configurator"
version = "0.2.0"

[dependencies]
auto-launch = "0.4.0"
druid = "0.8.3"
njupt_wifi_login_configuration = {path = "../configuration"}
once_cell = "1.18.0"
serde = {version = "1", features = ["derive"]}
serde_yaml = "0.9.22"
i18n-embed = {version= "0.14.1", features = ["fluent-system", "desktop-requester"]}
i18n-embed-fl = "0.7.0"
rust-embed = "8.2.0"
