[package]
edition = "2021"
name = "njupt_wifi_login_configurator"
version = "0.1.1"

[dependencies]
auto-launch = "0.4.0"
druid = "0.7.0"
serde = {version = "1", features = ["derive"]}
serde_yaml = "0.9.14"
once_cell = "1.15.0"